trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: Deployment_OnPrem

jobs:
  - job: Tests
    strategy:
      matrix:
        server2016:
          vmName: PRGPSDSRV16
        windows10:
          vmName: PRGPSDWIN10
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: ms-vscs-rm.scvmmapp.scvmmresourcedeployment-task.SCVMM@1
        inputs:
          ConnectedServiceName: 'product-readiness.SCVMM'
          VMList: $(vmName)
          CheckPointName: Initial
          ScopeFilter: CloudFiltering
          CloudFilter: OAK
          CreateBoundaryVM: false
          NoDetailedLogs: false
        displayName: 'SCVMM: Restore VM Checkpoint'

      - task: ms-vscs-rm.scvmmapp.scvmmresourcedeployment-task.SCVMM@1
        inputs:
          ConnectedServiceName: 'product-readiness.SCVMM'
          VMList: $(vmName)
          Action: StartVM
          ScopeFilter: CloudFiltering
          CloudFilter: OAK
          CreateBoundaryVM: false
          NoDetailedLogs: false
        displayName: 'SCVMM: Start VM'
      
      # Download secrets from Azure Key Vault
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: '$(azureSubscription)'
          KeyVaultName: 'Github-Samples'
          SecretsFilter: 'Username2, Password2'
          RunAsPreJob: false
      
      - task: WindowsMachineFileCopy@2
        inputs:
          sourcePath: $(Build.SourcesDirectory)
          machineNames: $(vmName)
          targetPath: 'C:\Test'
          adminUserName: $(Username2)
          adminPassword: $(Password2)
        displayName: 'Copy PowerShell script'

      - task: PowerShellOnTargetMachines@3
        inputs:
          machines: $(vmName)
          scriptType: filePath
          scriptPath: 'C:\Test\Install-PIServer.ps1'
          scriptArguments: '-sql .\SQL\SETUP.EXE -piserver .\PIServer.exe -pilicdir C:\Test -afdatabase TestDatabase -pibundle .\PIProcessBook.exe -remote'
          workingDirectory: 'C:\Test'
          userName: .\$(Username)
          userPassword: $(Password2)
        displayName: 'Run PowerShell script'

      - task: PowerShellOnTargetMachines@3
        inputs:
          machines: $(vmName)
          communicationProtocol: http
          scriptType: filePath
          scriptPath: 'C:\Test\Verify-PIServer.ps1'
          userName: .\$(Username)
          userPassword: $(Password2)
        displayName: 'Run tests'

      - task: ms-vscs-rm.scvmmapp.scvmmresourcedeployment-task.SCVMM@1
        inputs:
          ConnectedServiceName: 'product-readiness.SCVMM'
          VMList: $(vmName)
          Action: StopVM
          ScopeFilter: CloudFiltering
          CloudFilter: OAK
          CreateBoundaryVM: false
          NoDetailedLogs: false
        displayName: 'SCVMM: Stop VM'
        condition: always()

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          skipPolaris: true
